project_id = "twcjjisnxmfpseksqnhb"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17


[functions.create-admin-user]
enabled = true
verify_jwt = true
entrypoint = "./functions/create-admin-user/index.ts"

[functions.delete-admin-user]
enabled = true
verify_jwt = true
entrypoint = "./functions/delete-admin-user/index.ts"

[functions.reset-admin-password]
enabled = true
verify_jwt = true
entrypoint = "./functions/reset-admin-password/index.ts"
